# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Soil_Grids_DownloaderDialog
                                 A QGIS plugin
 This plug-in is used to download soil properties data from soil grids
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-05
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Ilias Machairas
        email                : iliasmachairas@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Soil_Grids_Downloader_dialog_base.ui'))


class Soil_Grids_DownloaderDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(Soil_Grids_DownloaderDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    # check it again
    def get_selected_properties(self):
        """Return a list of selected properties based on checked checkboxes."""
        selected_properties = []

        # Check if each checkbox is ticked and add the corresponding property to the list
        if self.checkBox_tab2_sand.isChecked():
            selected_properties.append('sand')
        if self.checkBox_tab2_clay.isChecked():
            selected_properties.append('clay')
        if self.checkBox_tab2_silt.isChecked():
            selected_properties.append('silt')
        if self.checkBox_tab2_nitrogen.isChecked():
            selected_properties.append('nitrogen')
        if self.checkBox_tab2_soc.isChecked():
            selected_properties.append('soc')

        return selected_properties