# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Soil_Grids_DownloaderDialog
                                 A QGIS plugin
 This plug-in is used to download soil properties data from soil grids
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-05
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Ilias Machairas
        email                : iliasmachairas@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QButtonGroup
from qgis.core import QgsMapLayerProxyModel

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Soil_Grids_Downloader_dialog_base.ui'))

# Widgets shown only in "Draw on map" raster AOI mode
_RASTER_DRAW_WIDGETS = (
    "pushButton_draw_extent", "label_raster_top", "lineEdit_raster_top",
    "label_raster_left", "lineEdit_raster_left", "label_raster_right", "lineEdit_raster_right",
    "label_raster_bottom", "lineEdit_raster_bottom",
)
# Widgets shown only in "From layer" raster AOI mode
_RASTER_LAYER_WIDGETS = ("comboBox_raster_aoi_layer", "label_raster_aoi_layer_hint")


class Soil_Grids_DownloaderDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(Soil_Grids_DownloaderDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.comboBox_raster_aoi_layer.setFilters(QgsMapLayerProxyModel.Filter.PolygonLayer)

        self.rasterAoiGroup = QButtonGroup(self)
        self.rasterAoiGroup.addButton(self.radioBtn_raster_aoi_draw, 0)
        self.rasterAoiGroup.addButton(self.radioBtn_raster_aoi_layer, 1)
        self.radioBtn_raster_aoi_draw.toggled.connect(self._update_raster_aoi_mode)
        self._update_raster_aoi_mode()

    def _update_raster_aoi_mode(self):
        draw_mode = self.radioBtn_raster_aoi_draw.isChecked()
        for name in _RASTER_DRAW_WIDGETS:
            getattr(self, name).setVisible(draw_mode)
        for name in _RASTER_LAYER_WIDGETS:
            getattr(self, name).setVisible(not draw_mode)

    # check it again
    def get_selected_properties(self):
        """Return a list of selected properties based on checked checkboxes."""
        selected_properties = []

        # Check if each checkbox is ticked and add the corresponding property to the list
        if self.checkBox_tab2_sand.isChecked():
            selected_properties.append('sand')
        if self.checkBox_tab2_clay.isChecked():
            selected_properties.append('clay')
        if self.checkBox_tab2_silt.isChecked():
            selected_properties.append('silt')
        if self.checkBox_tab2_nitrogen.isChecked():
            selected_properties.append('nitrogen')
        if self.checkBox_tab2_soc.isChecked():
            selected_properties.append('soc')

        return selected_properties

    def get_selected_raster_properties(self):
        """Return a list of selected properties on the 'Download raster' tab."""
        selected_properties = []

        if self.checkBox_tab5_sand.isChecked():
            selected_properties.append('sand')
        if self.checkBox_tab5_clay.isChecked():
            selected_properties.append('clay')
        if self.checkBox_tab5_silt.isChecked():
            selected_properties.append('silt')
        if self.checkBox_tab5_nitrogen.isChecked():
            selected_properties.append('nitrogen')
        if self.checkBox_tab5_soc.isChecked():
            selected_properties.append('soc')

        return selected_properties

    def get_raster_aoi(self):
        """Return (xmin, ymin, xmax, ymax) as floats, raise ValueError if invalid."""
        try:
            top    = float(self.lineEdit_raster_top.text())
            bottom = float(self.lineEdit_raster_bottom.text())
            left   = float(self.lineEdit_raster_left.text())
            right  = float(self.lineEdit_raster_right.text())
        except ValueError:
            raise ValueError("Area of interest coordinates must be valid decimal numbers.")
        if left >= right or bottom >= top:
            raise ValueError("Invalid area of interest: left < right and bottom < top required.")
        return left, bottom, right, top  # xmin, ymin, xmax, ymax

    def set_raster_aoi(self, xmin, ymin, xmax, ymax):
        self.lineEdit_raster_left.setText(f"{xmin:.6f}")
        self.lineEdit_raster_right.setText(f"{xmax:.6f}")
        self.lineEdit_raster_bottom.setText(f"{ymin:.6f}")
        self.lineEdit_raster_top.setText(f"{ymax:.6f}")

    def get_raster_aoi_source(self):
        return "draw" if self.radioBtn_raster_aoi_draw.isChecked() else "layer"

    def get_raster_aoi_layer(self):
        """Return the QgsVectorLayer selected in the 'From layer' combo, or None."""
        return self.comboBox_raster_aoi_layer.currentLayer()